### ISSUE TITLE
projection issue? Error on using get_eddi()

### ISSUE THREAD

**Issue by ryanpeek** [earthlab/eddi#10]
Hi there, 
First, thanks for the great package, this is handy and I've enjoyed using it. Haven't touched it in awhile and tried to run it today, but keep getting this error:

`Error in !get("has_proj_def.dat", envir = .RGDAL_CACHE) : 
  invalid argument type`

I poked around in the function, and it looks like if I comment things out in the `get_eddi()` function, things run without trouble if the lines that check for valid projections get commented out:

```
r <- raster::stack(local_path) # raster approach
#out_proj_string <- "+init=epsg:4326"
  out_proj_string <- CRS("+init=epsg:4326")
  #proj_string_valid <- rgdal::checkCRSArgs(out_proj_string)[[1]]
  #stopifnot(proj_string_valid)
  raster::crs(r) <- out_proj_string
  r
```
I don't use raster much, but seems this may be the PROJ4/5+ situation...but not sure. I'm not an expert in that realm. I've bypassed the error check by commenting it out, and things run fine now (but sans the check). 

I'm on Mojave 10.14.6 and R 4.0.3, with most recent updated pkg versions.

Thx much.

**Comment by mbjoseph** [comment]
Thanks @ryanpeek! Fixed with f0809276e65a69e434d627d7f2404f92c11cd1f2
